Pizzeria-InForno/Models/Articoli.cs
using System.ComponentModel.DataAnnotations;

namespace Pizzeria_InForno.Models
{
    public class Articoli
    {
        [Key]
        public int IdArticolo { get; set; }
        [Required]
        public string NomeArticolo { get; set; }
        [Required]
        public string Descrizione { get; set; }
        [Required]
        public double Prezzo { get; set; }
        [Required]
        public string Immagine { get; set; }

        [Required]
        [Display(Name = "Tempi di consegna")]
        public int TempoConsegna { get; set; }



        // questa proprietà è stata aggiunta per permettere la navigazione
        public virtual ICollection<DettagliOrdine> DettagliOrdine { get; set; }
        public virtual ICollection<DettagliIngredienti> DettagliIngrediente { get; set; }
    }
}

Pizzeria-InForno/Controllers/OrdineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Pizzeria_InForno.Data;
using Pizzeria_InForno.Models;
using System.Security.Claims;

namespace Pizzeria_InForno.Controllers
{
    public class OrdineController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public OrdineController(ApplicationDbContext db, IWebHostEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
        }
        // BACKOFFICE SECTION

        // GET Ordine/Index - Tutti gli ordini
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Index()
        {
            var ordini = await _db.Ordini.Include(o => o.DettagliOrdine).ThenInclude(d => d.Articoli).Include(o => o.Utenti).ToListAsync();

            return View(ordini);
        }

        // GET Ordine/Dettagli
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Dettagli(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ordine = await _db.Ordini
                .Include(o => o.DettagliOrdine)
                    .ThenInclude(d => d.Articoli)
                        .ThenInclude(a => a.DettagliIngrediente)
                            .ThenInclude(di => di.Ingredienti)
                .FirstOrDefaultAsync(o => o.IdOrdine == id);
            if (ordine == null)
            {
                return RedirectToAction("index");
            }
            foreach (var dettaglio in ordine.DettagliOrdine)
            {
                var prezzoArticolo = dettaglio.Articoli.Prezzo + dettaglio.Articoli.DettagliIngrediente.Sum(di => di.Ingredienti.Prezzo);
                dettaglio.Articoli.Prezzo = prezzoArticolo * dettaglio.Quantita;

                dettaglio.Articoli.Immagine = Path.Combine("/", dettaglio.Articoli.Immagine);
            }
            return View(ordine);
        }
        // GET Ordine/Edit 
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            // questa query include anche l'utente che ha effettuato l'ordine per poter visualizzare il suo username
            var ordine = await _db.Ordini.Include(o => o.Utenti).FirstOrDefaultAsync(o => o.IdOrdine == id);
            if (ordine == null)
            {
                return NotFound();
            }
            ViewBag.Utente = new SelectListItem
            {
                Value = ordine.Utenti.IdUtente.ToString(),
                Text = ordine.Utenti.Username
            };
            return View(ordine);
        }

        // POST Ordine/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("IdOrdine, IdUtente, IndirizzoSpedizione, IsConsegnato, Note, Totale, DataOrdine")] Ordini ordine)
        {
            if (id != ordine.IdOrdine)
            {
                return NotFound();
            }
            // per evitare che l'utente modifichi l'ID dell'utente sul quale si vuole effettuare la modifica nell'edit dell'ordine
            var checkOriginalOrder = await _db.Ordini.AsNoTracking().FirstOrDefaultAsync(o => o.IdOrdine == id);
            var utente = await _db.Utenti.FindAsync(checkOriginalOrder.IdUtente);
            if (checkOriginalOrder.IdUtente != ordine.IdUtente)
            {
                TempData["error"] = "Non puoi modificare l'ID dell'utente";

                ViewBag.Utente = new SelectListItem
                {
                    Value = utente.IdUtente.ToString(),
                    Text = utente.Username
                };
                return View(ordine);
            }


            ModelState.Remove("Utenti");
            ModelState.Remove("DettagliOrdine");
            ModelState.Remove("DettagliIngredienti");
            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(ordine);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdineExists(ordine.IdOrdine))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Utente = new SelectListItem
            {
                Value = utente.IdUtente.ToString(),
                Text = utente.Username
            };
            return View(ordine);
        }

        private bool OrdineExists(int id)
        {
            return _db.Ordini.Any(e => e.IdOrdine == id);
        }

        // GET Ordine/Delete
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var ordine = await _db.Ordini.FirstOrDefaultAsync(m => m.IdOrdine == id);
            if (ordine == null)
            {
                return NotFound();
            }
            return View(ordine);
        }

        // POST Ordine/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ordine = await _db.Ordini.FindAsync(id);
            if (ordine != null)
            {
                _db.Ordini.Remove(ordine);
            }
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        [Authorize(Roles = "user, admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "user,admin")]
        [HttpPost]
        public async Task<IActionResult> Create([Bind("IdUtente, IndirizzoSpedizione, isConsegnato, note")] Ordini ordine)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null)
            {
                return RedirectToAction("Login", "Index");
            }

            ordine.IdUtente = int.Parse(userId);

            // Prendi il carrello dalla sessione
            var cartSession = HttpContext.Session.GetString("cartList");
            if (!string.IsNullOrEmpty(cartSession))
            {
                var cartList = JsonConvert.DeserializeObject<List<Carrello>>(cartSession);
                double prezzoTotale = 0;
                foreach (var item in cartList)
                {

                    var articolo = _db.Articoli.Include(a => a.DettagliIngrediente).ThenInclude(di => di.Ingredienti).Single(a => a.IdArticolo == item.Articoli.IdArticolo);
                    var prezzoIngredienti = articolo.DettagliIngrediente.Sum(di => di.Ingredienti.Prezzo);
                    prezzoTotale += (articolo.Prezzo + prezzoIngredienti) * item.Quantita;


                }

                // Imposta il prezzo dell'ordine
                ordine.Totale = prezzoTotale;
                ordine.DataOrdine = DateTime.Now;

                _db.Ordini.Add(ordine);
                await _db.SaveChangesAsync();

                foreach (var item in cartList)
                {
                    var dettagliOrdine = new DettagliOrdine
                    {
                        IdOrdine = ordine.IdOrdine,
                        IdArticolo = item.Articoli.IdArticolo,
                        Quantita = item.Quantita
                    };
                    _db.DettagliOrdine.Add(dettagliOrdine);
                }
                await _db.SaveChangesAsync();
                HttpContext.Session.Remove("cartList");
                TempData["success"] = "Ordine effettuato con successo";
            }

            return RedirectToAction("Index", "Home");
        }

        // GET Ordine/TotaleFatturatoInData da fetchare
        public async Task<IActionResult> TotaleFatturatoInData(DateTime date)
        {
            var fatturato = await _db.Ordini.Where(o => o.DataOrdine.Date == date.Date && o.IsConsegnato).SumAsync(o => o.Totale);
            return Json(fatturato);
        }

        // get Ordine/TotaleOrdiniEvasi da fetchare
        public async Task<IActionResult> TotaleOrdiniEvasi()
        {
            var totaleOrdiniEvasi = await _db.Ordini.Where(o => o.IsConsegnato).CountAsync();
            return Json(totaleOrdiniEvasi);
        }
    }
}

Pizzeria-InForno/Views/Articoli/CartView.cshtml
@model List<Carrello>
@{
    ViewData["Title"] = "CartView";
}

<div class="container">

    @if (!Model.Any())
    {
        
        <p class="alert bgNav text-white">Il carrello è vuoto</p>
    }
    else
    {
        @foreach (var item in Model)
        {
            <div class="row border border-1 border-secondary border-start-0 border-end-0 border-top-0 mb-3">
                <div class="col-7">
                    <div class="imgContainer">
                        <img class="img-fluid myImgPizza" src="@item.Articoli.Immagine" alt="@item.Articoli.NomeArticolo">
                    </div>
                    
                </div>
                <div class="col-5">
                    <div class="d-flex justify-content-between align-items-end">
                        <h5 class="card-title fs-1">Prodotto: @item.Articoli.NomeArticolo</h5>
                        <p class="fw-semibold fs-6 mb-0">Quantità: @item.Quantita</p>
                    </div>
                    <div class="d-flex">
                        <p id="total-@item.Articoli.IdArticolo" class="total fw-semibold fs-6 mb-0">Prezzo: @item.Totale<span>€</span></p>
                    </div>
                        <button class="btn-remove btn btn-danger" data-id="@item.Articoli.IdArticolo">Rimuovi</button>
                </div>
            </div>
        }

        <div class="d-flex flex-column align-items-end">
            <h2 class="text-end mb-0">Totale dell'ordine: <span id="total-order">@ViewBag.PrezzoTotale<span>€</span></span></h2>
            <a class="btn btn-primary" asp-controller="Ordine" asp-action="Create">Crea Ordine</a>
        </div>
    }
</div>

<script>
    document.querySelectorAll('.btn-remove').forEach(button => {
        button.addEventListener('click', async function () {
            const id = this.getAttribute('data-id'); // Assumendo che ogni pulsante abbia un attributo data-id con l'ID dell'articolo
            try {
                const response = await fetch('/Articoli/RemoveFromCart', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ Articoli: { IdArticolo: id } })
                });
                if (response.ok) {
                    // Aggiorna la vista del carrello o mostra un messaggio di successo
                    location.reload();
                } else {
                    // Mostra un messaggio di errore
                    alert("Si è verificato un errore durante la rimozione dell'articolo dal carrello.");
                }
            } catch (error) {
                // Gestisci eventuali errori di rete
                alert("Si è verificato un errore di rete.");
            }
        });
    });
</script>

Pizzeria-InForno/Views/Articoli/Create.cshtml
@model Pizzeria_InForno.Models.Articoli

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Articoli</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeArticolo" class="control-label"></label>
                <input asp-for="NomeArticolo" class="form-control" />
                <span asp-validation-for="NomeArticolo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descrizione" class="control-label"></label>
                <input asp-for="Descrizione" class="form-control" />
                <span asp-validation-for="Descrizione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezzo" class="control-label"></label>
                <input asp-for="Prezzo" class="form-control" />
                <span asp-validation-for="Prezzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Immagine" class="control-label"></label>
                <input type="file" name="Immagine" asp-for="Immagine" class="form-control" />
                <span asp-validation-for="Immagine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TempoConsegna" class="control-label"></label>
                <input asp-for="TempoConsegna" class="form-control" />
                <span asp-validation-for="TempoConsegna" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Ingredienti">Ingredienti</label>
                @Html.ListBox("Ingredienti", (MultiSelectList)ViewBag.Ingredienti, new { @class = "form-control" })
                <button type="button" onclick="addIngredient()">Aggiungi</button>
            </div>
            <div id="listaIngredientiSelezionati" class="d-flex">

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Script{
    <script>
        let selectedIngredients = [];   
        let addIngredient = () => {
            let select = document.getElementById("Ingredienti");
            let idIngrediente = select.value;
            let nomeIngrediente = select.options[select.selectedIndex].text;
            if (!selectedIngredients.includes(idIngrediente)) {
                selectedIngredients.push(idIngrediente);
                let list = document.getElementById("listaIngredientiSelezionati");

                // Crea un div contenitore per l'ingrediente
                let container = document.createElement("div");
                container.id = "container-" + idIngrediente;

                // Crea un paragrafo per il nome dell'ingrediente
                let ingrediente = document.createElement("p");
                ingrediente.id = "ingrediente-" + idIngrediente;
                ingrediente.innerHTML = nomeIngrediente;

                // Crea un pulsante per rimuovere l'ingrediente
                let removeButton = document.createElement("button");
                removeButton.innerHTML = "Rimuovi";
                removeButton.type = "button";
                removeButton.onclick = () => removeIngredient(idIngrediente);

                // Aggiunge l'ingrediente e il pulsante di rimozione al contenitore
                container.appendChild(ingrediente);
                container.appendChild(removeButton);

                // Aggiunge il contenitore alla lista
                list.appendChild(container);

                // Crea un campo nascosto per l'ID dell'ingrediente
                let hiddenField = document.createElement("input");
                hiddenField.type = "hidden";
                hiddenField.name = "ingredientiSelezionati";
                hiddenField.value = idIngrediente;

                // Aggiunge il campo nascosto al form
                let form = document.querySelector("form");
                form.appendChild(hiddenField);
            }
        }
        let removeIngredient = (idIngrediente) => {
            let index = selectedIngredients.indexOf(idIngrediente);
            if (index > -1) {
                selectedIngredients.splice(index, 1);
                let container = document.getElementById("container-" + idIngrediente);
                container.parentNode.removeChild(container);

                // Rimuove il campo nascosto dal form
                let hiddenField = document.querySelector(`input[value="${idIngrediente}"]`);
                hiddenField.parentNode.removeChild(hiddenField);
            }
        }
    </script>
}

Pizzeria-InForno/Views/Articoli/Delete.cshtml
@model Pizzeria_InForno.Models.Articoli

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Articoli</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeArticolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeArticolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descrizione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descrizione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezzo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Immagine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Immagine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TempoConsegna)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ingredienti)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ingredienti)
        </dd> *@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdArticolo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Pizzeria-InForno/Views/Articoli/Details.cshtml
@model Pizzeria_InForno.Models.Articoli

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Articoli</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeArticolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeArticolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descrizione)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descrizione)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezzo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Immagine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Immagine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TempoConsegna)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TempoConsegna)
        </dd>

    </dl>
    
    <div class="mt-5">
        <h4>Ingredienti</h4>
        <hr/>
        <dl class="row">
            @foreach (var item in Model.DettagliIngrediente)
            {
                <dt class = "col-sm-2">
                    @Html.DisplayFor(modelItem => item.Ingredienti.NomeIngrediente)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(modelItem => item.Ingredienti.Prezzo)
                </dd>
            }
        </dl>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdArticolo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Pizzeria-InForno/Views/Articoli/Edit.cshtml
@model Pizzeria_InForno.Models.Articoli

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Articoli</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdArticolo" />
            <div class="form-group">
                <label asp-for="NomeArticolo" class="control-label"></label>
                <input asp-for="NomeArticolo" class="form-control" />
                <span asp-validation-for="NomeArticolo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descrizione" class="control-label"></label>
                <input asp-for="Descrizione" class="form-control" />
                <span asp-validation-for="Descrizione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezzo" class="control-label"></label>
                <input asp-for="Prezzo" class="form-control" />
                <span asp-validation-for="Prezzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Immagine" class="control-label"></label>
                <input type="file" asp-for="Immagine" class="form-control" />
                <span asp-validation-for="Immagine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TempoConsegna" class="control-label"></label>
                <input asp-for="TempoConsegna" class="form-control" />
                <span asp-validation-for="TempoConsegna" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Ingredienti" class="control-label"></label>
                <input asp-for="Ingredienti" class="form-control" />
                <span asp-validation-for="Ingredienti" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Pizzeria-InForno/Views/Articoli/Index.cshtml
@model IEnumerable<Pizzeria_InForno.Models.Articoli>

@{
    ViewData["Title"] = "Index";
}


<h1 class="myTextColor mb-3">Articoli</h1>

<div class="d-flex">
<p>
    <a asp-action="Create" class="btn btn-sm btn-success me-3">Nuovo Prodotto</a>
</p>
    <p>
        <a asp-action="Index" asp-controller="Ingredienti" class="btn btn-sm btn-warning me-3">Gestione ingredienti</a>
    </p>
    <p>
        <a asp-action="Index" asp-controller="Ordine" class="btn btn-sm btn-warning me-3">Gestione ordini</a>
    </p>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeArticolo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descrizione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezzo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Immagine)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TempoConsegna)
            </th>
            @* <th>
                @Html.DisplayNameFor(model => model.Ingredienti)
            </th> *@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeArticolo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descrizione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezzo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Immagine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TempoConsegna)
            </td>
            @* <td>
                @Html.DisplayFor(modelItem => item.Ingredienti)
            </td> *@
            <td>
                <a class="btn btn-sm btn-success" asp-action="Edit" asp-route-id="@item.IdArticolo">Edit</a> 
                <a class="btn btn-sm btn-warning" asp-action="Details" asp-route-id="@item.IdArticolo">Details</a> 
                <a class="btn btn-sm btn-outline-danger" asp-action="Delete" asp-route-id="@item.IdArticolo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>