Pizzeria-InForno/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Pizzeria_InForno.Data;
using Pizzeria_InForno.Models;
using System.Security.Claims;

namespace Pizzeria_InForno.Controllers
{
    public class LoginController : Controller
    {
        // Memorizzo l'istanza di ApplicationDbContext in _db
        // Privata perché così è accessibile solo all'interno di questa classe
        // readonly significa che non posso midificarla
        private readonly ApplicationDbContext _db;
        // IAuthenticationSchemeProvider è un servizio che fornisce le informazioni sui provider di autenticazione disponibili
        // Tramite uno schema di autenticazione che possono esseere Cookie o Bearer Tokens, possiamo associare un nome ad una particolare configurazione di autenticazione
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        // Questo è un costruttore che assegna i valori dei parametri ai campi privati corrispondenti
        public LoginController(ApplicationDbContext db, IAuthenticationSchemeProvider schemeProvider)
        {
            _db = db;
            _schemeProvider = schemeProvider;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ActionName("Index")]
        [HttpPost]
        public async Task<IActionResult> Login(Utenti utente)
        {
            // Query per trovare l'utente nel db
            var dbUser = _db.Utenti.FirstOrDefault(u => u.Username == utente.Username);

            // Se la query non trova niente ci restituisce il temp data da stampare nella view
            if (dbUser == null)
            {
                TempData["error"] = "Questo Nome Utente non esiste";
                return View();
            }
            if (dbUser.Password != utente.Password)
            {
                TempData["error"] = "Credenziali non valide";
                return View();
            }
            // Trovato l'utente, se la password che inseriamo coincide con quella presente sul db possiamo procedere
            // Salviamo nei claims le informazioni sull'utente autenticato
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, dbUser.Username),
                new Claim(ClaimTypes.Role, dbUser.Ruolo),
                new Claim(ClaimTypes.NameIdentifier, dbUser.IdUtente.ToString())
            };
            // Salviamo in questa variabile l'identità dell'utente autenticato
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
            TempData["success"] = "Login effettuato con successo";

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            TempData["success"] = "Logout effettuato con successo";
            return RedirectToAction("Index", "Home");
        }
    }
}

Pizzeria-InForno/Controllers/UtentiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pizzeria_InForno.Data;
using Pizzeria_InForno.Models;
using System.Security.Claims;

namespace Pizzeria_InForno.Controllers
{
    public class UtentiController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UtentiController(ApplicationDbContext db)
        {

            _db = db;

        }
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        // Elimino dal bind di utente l'attributo Ruolo
        public IActionResult SignUp([Bind("Username, Password")] Utenti utente)
        {
            // Rimuovo l'errore relativo all'attributo ordini non passandolo al model
            ModelState.Remove("ordini");
            // Faccio un check del model, se è valido proseguo
            if (ModelState.IsValid)
            {
                // Controllo se c'è già un utente registrato con lo stesso username
                if (_db.Utenti.Any(u => u.Username == utente.Username))
                {
                    TempData["error"] = "Nome utente già in uso";
                    return View(utente);
                }
                // Se non c'è un utente con lo stesso username procedo con la registrazione e faccio una insert nel DB
                _db.Utenti.Add(utente);
                _db.SaveChanges();
                TempData["success"] = "Registrazione avvenuta con successo";
                return RedirectToAction("Index", "Login");

            }
            else
            {
                TempData["error"] = "Errore nella registrazione";
                return View(utente);
            }
        }

        // Get Utente/Ordine/RiepilogoOrdini
        [Authorize(Roles = "user,admin")]
        public async Task<IActionResult> RiepilogoOrdini()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var ordini = await _db.Ordini.Include(o => o.DettagliOrdine).ThenInclude(d => d.Articoli).Where(o => o.IdUtente == int.Parse(userId)).ToListAsync();
            return View(ordini);
        }

        // GET Utente/Ordine/DettagliOrdine
        [Authorize(Roles = "user,admin")]
        public async Task<IActionResult> DettagliOrdine(int? idOrdine)
        {
            if (idOrdine == null)
            {
                return NotFound();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var ordine = await _db.Ordini.Include(o => o.DettagliOrdine).ThenInclude(d => d.Articoli).ThenInclude(a => a.DettagliIngrediente).ThenInclude(di => di.Ingredienti).FirstOrDefaultAsync(o => o.IdOrdine == idOrdine && o.IdUtente == int.Parse(userId));
            if (ordine == null)
            {
                return RedirectToAction("RiepilogoOrdini");
            }
            foreach (var dettaglio in ordine.DettagliOrdine)
            {
                var prezzoArticolo = dettaglio.Articoli.Prezzo + dettaglio.Articoli.DettagliIngrediente.Sum(di => di.Ingredienti.Prezzo);
                dettaglio.Articoli.Prezzo = prezzoArticolo * dettaglio.Quantita;

                dettaglio.Articoli.Immagine = Path.Combine("/", dettaglio.Articoli.Immagine);
            }
            return View(ordine);
        }

        // GET Utente/Ordine/DeleteOrdine   
        [Authorize(Roles = "user,admin")]
        public async Task<IActionResult> DeleteOrdine(int? idOrdine)
        {
            if (idOrdine == null)
            {
                return NotFound();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var ordine = await _db.Ordini.Include(o => o.DettagliOrdine).FirstOrDefaultAsync(o => o.IdOrdine == idOrdine && o.IdUtente == int.Parse(userId));
            if (ordine == null)
            {
                return RedirectToAction("RiepilogoOrdini");
            }

            return View(ordine);
        }

        // POST Utente/Ordine/DeleteOrdine
        [HttpPost, ActionName("DeleteOrdine")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "user, admin")]
        public async Task<IActionResult> DeleteOrdineConfirmed(int idOrdine)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var ordine = await _db.Ordini.Include(o => o.DettagliOrdine).FirstOrDefaultAsync(o => o.IdOrdine == idOrdine && o.IdUtente == int.Parse(userId));
            if (ordine == null)
            {
                return RedirectToAction("RiepilogoOrdini");
            }
            _db.Ordini.Remove(ordine);
            await _db.SaveChangesAsync();
            return RedirectToAction("RiepilogoOrdini");
        }
    }
}

Pizzeria-InForno/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizzeria_InForno</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pizzeria_InForno.styles.css" asp-append-version="true" />
</head>
<body class="bgBody">
    <header class="position-relative ">
        
        
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 bgNav">
        
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/logo/InForno.png" style="width: 100px" class="img-fluid" alt="Responsive image"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        
                        {
                        <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Articoli" asp-action="Index">BackOffice</a>
                        </li>
                            
                        }
                    </ul>
                    <ul class="navbar-nav ">   
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white text-decoration-none" asp-area="" asp-controller="Utenti" asp-action="RiepilogoOrdini">Riepilogo Ordini</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white text-decoration-none" asp-area="" asp-controller="Articoli" asp-action="CartView">Carrello</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white text-decoration-none" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }

                    </ul>
            @if (TempData["success"] != null)
            {
                
                    <p id="success-alert" class="alert alert-success position-absolute top-100 end-0 me-5 ">@TempData["success"]</p>
                
            }
            @if (TempData["error"] != null)
            {
                
                        <p id="error-alert" class="alert alert-danger position-absolute top-100 end-0 me-5 ">@TempData["error"]</p>
                 
            }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Pizzeria_InForno - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        window.addEventListener("DOMContentLoaded", () => {
            let successAlert = document.getElementById("success-alert");
            if (successAlert) {
                setTimeout(() => { 
                    successAlert.style.display = "none";
                    successAlert.style.left = "90%";
                },2000)
            }
            let errorAlert = document.getElementById("error-alert");
            if (errorAlert) {
                setTimeout(() => { 
                    errorAlert.style.display = "none";
                    errorAlert.style.left = "90%";
                },2000)
            }
        })
    </script>
    @RenderSection("Script", required: false)
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>