Pizzeria-InForno/Models/Ingredienti.cs
using System.ComponentModel.DataAnnotations;

namespace Pizzeria_InForno.Models
{
    public class Ingredienti
    {
        [Key]
        public int IdIngrediente { get; set; }
        [Required]
        [Display(Name = "Nome")]
        public string NomeIngrediente { get; set; }
        [Required]
        public double Prezzo { get; set; }

        public virtual ICollection<DettagliIngredienti> DettagliIngredienti { get; set; }
    }
}

Pizzeria-InForno/Controllers/ArticoliController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Pizzeria_InForno.Data;
using Pizzeria_InForno.Models;

namespace Pizzeria_InForno.Controllers
{

    public class ArticoliController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ArticoliController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Articoli
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Index()
        {
            var articoli = await _db.Articoli.Include(a => a.DettagliIngrediente).ThenInclude(di => di.Ingredienti).ToListAsync();
            foreach (var articolo in articoli)
            {
                articolo.Prezzo += articolo.DettagliIngrediente.Sum(di => di.Ingredienti.Prezzo);
            }

            return View(articoli);
        }


        // GET: Articoli/Details/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articoli = await _db.Articoli
                .Include(a => a.DettagliIngrediente)
                .ThenInclude(di => di.Ingredienti)
                .FirstOrDefaultAsync(m => m.IdArticolo == id);
            if (articoli == null)
            {
                return NotFound();
            }

            return View(articoli);
        }

        // GET: Articoli/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewBag.Ingredienti = new MultiSelectList(_db.Ingredienti, "IdIngrediente", "NomeIngrediente");
            return View();
        }

        // POST: Articoli/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("NomeArticolo,Descrizione,Prezzo,TempoConsegna")] Articoli articoli, List<int> ingredientiSelezionati, IFormFile Immagine)
        {
            ModelState.Remove("DettagliOrdine");
            ModelState.Remove("DettagliIngrediente");
            ModelState.Remove("Immagine");
            if (ModelState.IsValid)
            {
                if (_db.Articoli.Any(a => a.NomeArticolo == articoli.NomeArticolo))
                {
                    TempData["error"] = "Esiste già un articolo con questo nome";
                    ViewBag.Ingredienti = new MultiSelectList(_db.Ingredienti, "IdIngrediente", "NomeIngrediente");
                    return View(articoli);
                }
                if (Immagine != null && Immagine.Length > 0)
                {
                    var fileName = Path.GetFileName(Immagine.FileName);
                    var path = Path.Combine(_hostEnvironment.WebRootPath, "img", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await Immagine.CopyToAsync(fileStream);
                    }
                    articoli.Immagine = Path.Combine("img", fileName);
                }

                _db.Articoli.Add(articoli);
                await _db.SaveChangesAsync();
                foreach (var idIngrediente in ingredientiSelezionati)
                {
                    var dettagliIngrediente = new DettagliIngredienti
                    {
                        IdArticolo = articoli.IdArticolo,
                        IdIngrediente = idIngrediente
                    };

                    _db.DettagliIngrediente.Add(dettagliIngrediente);
                }
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Ingredienti = new MultiSelectList(_db.Ingredienti, "IdIngrediente", "NomeIngrediente");
            return View(articoli);
        }

        // GET: Articoli/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articoli = await _db.Articoli.FindAsync(id);
            if (articoli == null)
            {
                return NotFound();
            }
            return View(articoli);
        }

        // POST: Articoli/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("IdArticolo,NomeArticolo,Descrizione,Prezzo,Immagine,TempoConsegna")] Articoli articoli, IFormFile Immagine)
        {
            if (id != articoli.IdArticolo)
            {
                return NotFound();
            }

            ModelState.Remove("DettagliOrdine");
            ModelState.Remove("DettagliIngrediente");

            if (ModelState.IsValid)
            {
                try
                {
                    if (_db.Articoli.Any(a => a.NomeArticolo == articoli.NomeArticolo && a.IdArticolo != articoli.IdArticolo))
                    {
                        TempData["error"] = "Questo nome è associato ad un altro articolo.";
                        return View(articoli);
                    }
                    if (Immagine != null && Immagine.Length > 0)
                    {
                        var fileName = Path.GetFileName(Immagine.FileName);
                        var path = Path.Combine(_hostEnvironment.WebRootPath, "img", fileName);
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await Immagine.CopyToAsync(fileStream);
                        }
                        articoli.Immagine = Path.Combine("img", fileName);
                    }
                    _db.Update(articoli);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticoliExists(articoli.IdArticolo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(articoli);
        }

        // GET: Articoli/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var articoli = await _db.Articoli
                .FirstOrDefaultAsync(m => m.IdArticolo == id);
            if (articoli == null)
            {
                return NotFound();
            }

            return View(articoli);
        }

        // POST: Articoli/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var articoli = await _db.Articoli.FindAsync(id);
            if (articoli != null)
            {
                _db.Articoli.Remove(articoli);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticoliExists(int id)
        {
            return _db.Articoli.Any(e => e.IdArticolo == id);
        }

        [Authorize(Roles = "user, admin")]
        [HttpPost]
        // Questo metodo aggiunge un articolo al carrello

        public void AddToCart([FromBody] Carrello carrello)
        {
            int id = carrello.Articoli.IdArticolo;
            int quantity = carrello.Quantita;
            // Variabile che ci dice se l'articolo è già presente nel carrello
            bool isExist = false;
            // Query per trovare l'articolo nel db
            var articolo = _db.Articoli.Find(id);

            if (articolo != null)
            {
                // Prendo il carrello dalla sessione
                var cartSession = HttpContext.Session.GetString("cartList");
                if (cartSession != null)
                {
                    // dal momendo che il carrello è una lista di articoli, deserializziamo la stringa in una lista di articoli

                    List<Carrello> cart = JsonConvert.DeserializeObject<List<Carrello>>(cartSession);
                    // scorriamo la lista di articoli e se l'articolo è già presente nel carrello incrementiamo la quantità
                    foreach (var item in cart)
                    {
                        if (item.Articoli.IdArticolo == id)
                        {
                            item.Quantita += quantity;
                            // Serializziamo la lista di articoli in una stringa e la salviamo nella sessione
                            HttpContext.Session.SetString("cartList", JsonConvert.SerializeObject(cart));
                            isExist = true;
                        }
                    }
                }
                // Se l'articolo non è presente nel carrello, lo aggiungiamo
                if (!isExist)
                {
                    // Creiamo un nuovo oggetto articoliPerCarrello che è la mia classe boilerplate di articoli e gli assegniamo i valori dell'articolo

Pizzeria-InForno/Controllers/IngredientiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pizzeria_InForno.Data;
using Pizzeria_InForno.Models;

namespace Pizzeria_InForno.Controllers
{
    public class IngredientiController : Controller
    {
        private readonly ApplicationDbContext _db;

        public IngredientiController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: Ingredienti
        public async Task<IActionResult> Index()
        {
            return View(await _db.Ingredienti.ToListAsync());
        }

        // GET: Ingredienti/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredienti = await _db.Ingredienti
                .FirstOrDefaultAsync(m => m.IdIngrediente == id);
            if (ingredienti == null)
            {
                return NotFound();
            }

            return View(ingredienti);
        }

        // GET: Ingredienti/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ingredienti/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NomeIngrediente,Prezzo")] Ingredienti ingredienti)
        {
            ModelState.Remove("DettagliIngredienti");
            if (ModelState.IsValid)
            {
                if (_db.Ingredienti.Any(i => i.NomeIngrediente == ingredienti.NomeIngrediente))
                {
                    TempData["error"] = "Esiste già un ingrediente con questo nome";
                    return View(ingredienti);
                }
                _db.Add(ingredienti);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ingredienti);
        }

        // GET: Ingredienti/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredienti = await _db.Ingredienti.FindAsync(id);
            if (ingredienti == null)
            {
                return NotFound();
            }
            return View(ingredienti);
        }

        // POST: Ingredienti/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdIngrediente,NomeIngrediente,Prezzo")] Ingredienti ingredienti)
        {
            if (id != ingredienti.IdIngrediente)
            {
                return NotFound();
            }

            ModelState.Remove("DettagliIngredienti");
            if (ModelState.IsValid)
            {
                try
                {
                    if (_db.Ingredienti.Any(a => a.NomeIngrediente == ingredienti.NomeIngrediente && a.IdIngrediente != ingredienti.IdIngrediente))
                    {
                        TempData["error"] = "Questo nome è associato ad un altro articolo.";
                        return View(ingredienti);
                    }
                    _db.Update(ingredienti);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IngredientiExists(ingredienti.IdIngrediente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ingredienti);
        }

        // GET: Ingredienti/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ingredienti = await _db.Ingredienti
                .FirstOrDefaultAsync(m => m.IdIngrediente == id);
            if (ingredienti == null)
            {
                return NotFound();
            }

            return View(ingredienti);
        }

        // POST: Ingredienti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ingredienti = await _db.Ingredienti.FindAsync(id);
            if (ingredienti != null)
            {
                _db.Ingredienti.Remove(ingredienti);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IngredientiExists(int id)
        {
            return _db.Ingredienti.Any(e => e.IdIngrediente == id);
        }
    }
}

Pizzeria-InForno/Views/Ingredienti/Create.cshtml
@model Pizzeria_InForno.Models.Ingredienti

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ingredienti</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeIngrediente" class="control-label"></label>
                <input asp-for="NomeIngrediente" class="form-control" />
                <span asp-validation-for="NomeIngrediente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezzo" class="control-label"></label>
                <input asp-for="Prezzo" class="form-control" />
                <span asp-validation-for="Prezzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Pizzeria-InForno/Views/Ingredienti/Delete.cshtml
@model Pizzeria_InForno.Models.Ingredienti

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingredienti</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeIngrediente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeIngrediente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezzo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdIngrediente" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Pizzeria-InForno/Views/Ingredienti/Details.cshtml
@model Pizzeria_InForno.Models.Ingredienti

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ingredienti</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeIngrediente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeIngrediente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezzo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezzo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdIngrediente">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Pizzeria-InForno/Views/Ingredienti/Edit.cshtml
@model Pizzeria_InForno.Models.Ingredienti

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ingredienti</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdIngrediente" />
            <div class="form-group">
                <label asp-for="NomeIngrediente" class="control-label"></label>
                <input asp-for="NomeIngrediente" class="form-control" />
                <span asp-validation-for="NomeIngrediente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezzo" class="control-label"></label>
                <input asp-for="Prezzo" class="form-control" />
                <span asp-validation-for="Prezzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Pizzeria-InForno/Views/Ingredienti/Index.cshtml
@model IEnumerable<Pizzeria_InForno.Models.Ingredienti>

@{
    ViewData["Title"] = "Index";
}

<h1 class="myTextColor mb-3">Ingredienti</h1>

<div class="d-flex">
<p>
        <a asp-action="Create" class="btn btn-sm btn-success me-3">Create New</a>
</p>
    <p>
        <a asp-action="Index" asp-controller="Articoli" class="btn btn-sm btn-outline-danger me-3">Torna alla gesione Articoli</a>
    </p>

</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeIngrediente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezzo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeIngrediente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezzo)
            </td>
            <td>
                    <a class="btn btn-sm btn-success" asp-action="Edit" asp-route-id="@item.IdIngrediente">Edit</a> 
                    <a class="btn btn-sm btn-warning" asp-action="Details" asp-route-id="@item.IdIngrediente">Details</a> 
                    <a class="btn btn-sm btn-outline-danger" asp-action="Delete" asp-route-id="@item.IdIngrediente">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>